CREATE TABLE 1 (
	Game_World_Tile_ID INTEGER NOT NULL,
	Game_World_ID INTEGER NOT NULL,
	CONSTRAINT PK_18 PRIMARY KEY (Game_World_Tile_ID, Game_World_ID)
	);
CREATE INDEX TC_14 ON 1 (Game_World_Tile_ID );
CREATE INDEX TC_15 ON 1 (Game_World_ID );
CREATE TABLE Game_World (
	ID INTEGER NOT NULL,
	World_name INTEGER NOT NULL,
	World_size VARCHAR ( 255 ) NOT NULL,
	Game_World_ID INTEGER NOT NULL,
	Game_ID INTEGER,
	CONSTRAINT PK_Game_World1 PRIMARY KEY (Game_World_ID)
	);
CREATE INDEX TC_Game_World8 ON Game_World (Game_ID );
CREATE TABLE Player_Move (
	ID INTEGER NOT NULL,
	Player_ID INTEGER NOT NULL,
	Timer DATE NOT NULL,
	Game_ID INTEGER NOT NULL,
	Move_X INTEGER NOT NULL,
	Move_Y INTEGER NOT NULL,
	Player_Move_ID INTEGER NOT NULL,
	Player_ID INTEGER NOT NULL,
	CONSTRAINT PK_Player_Move4 PRIMARY KEY (Player_Move_ID)
	);
CREATE INDEX TC_Player_Move9 ON Player_Move (Player_ID );
CREATE TABLE Player (
	ID INTEGER NOT NULL,
	Username VARCHAR ( 255 ) NOT NULL,
	Password VARCHAR ( 255 ) NOT NULL,
	E-mail VARCHAR ( 255 ) NOT NULL,
	Avatar VARCHAR ( 255 ) NOT NULL,
	Player_ID INTEGER NOT NULL,
	CONSTRAINT PK_Player0 PRIMARY KEY (Player_ID)
	);
CREATE TABLE Game_World_Tile (
	ID INTEGER NOT NULL,
	Game_World_ID INTEGER NOT NULL,
	Game_Tile_ID INTEGER NOT NULL,
	Game_World_X INTEGER NOT NULL,
	Game_World_Y INTEGER NOT NULL,
	Game_World_Tile_ID INTEGER NOT NULL,
	Game_Tile_ID INTEGER NOT NULL,
	CONSTRAINT PK_Game_World_Tile7 PRIMARY KEY (Game_World_Tile_ID)
	);
CREATE INDEX TC_Game_World_Tile11 ON Game_World_Tile (Game_Tile_ID );
CREATE TABLE 0 (
	Game_ID INTEGER NOT NULL,
	Player_ID INTEGER NOT NULL,
	CONSTRAINT PK_03 PRIMARY KEY (Game_ID, Player_ID)
	);
CREATE INDEX TC_00 ON 0 (Game_ID );
CREATE INDEX TC_01 ON 0 (Player_ID );
CREATE TABLE Game_Tile_Image (
	ID INTEGER NOT NULL,
	Path VARCHAR ( 255 ) NOT NULL,
	Tile_size VARCHAR ( 255 ) NOT NULL,
	Game_Tile_Image_ID INTEGER NOT NULL,
	Game_Tile_ID INTEGER NOT NULL,
	CONSTRAINT PK_Game_Tile_Image5 PRIMARY KEY (Game_Tile_Image_ID)
	);
CREATE INDEX TC_Game_Tile_Image10 ON Game_Tile_Image (Game_Tile_ID );
CREATE TABLE Game_Tile (
	ID INTEGER NOT NULL,
	Name VARCHAR ( 255 ) NOT NULL,
	Game_Tile_Image VARCHAR ( 255 ) NOT NULL,
	Tile_ID INTEGER NOT NULL,
	Can_move SMALLINT NOT NULL,
	Game_Tile_ID INTEGER NOT NULL,
	CONSTRAINT PK_Game_Tile6 PRIMARY KEY (Game_Tile_ID)
	);
CREATE TABLE Game (
	ID INTEGER NOT NULL,
	Game_Start DATE NOT NULL,
	Game_End DATE NOT NULL,
	Winner_ID INTEGER NOT NULL,
	Game_ID INTEGER NOT NULL,
	CONSTRAINT PK_Game2 PRIMARY KEY (Game_ID)
	);
ALTER TABLE Game_World_Tile ADD CONSTRAINT FK_Game_World_Tile7 FOREIGN KEY (Game_Tile_ID) REFERENCES Game_Tile (Game_Tile_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE 0 ADD CONSTRAINT FK_00 FOREIGN KEY (Game_ID) REFERENCES Game (Game_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE 0 ADD CONSTRAINT FK_01 FOREIGN KEY (Player_ID) REFERENCES Player (Player_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Game_World ADD CONSTRAINT FK_Game_World2 FOREIGN KEY (Game_ID) REFERENCES Game (Game_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE 1 ADD CONSTRAINT FK_14 FOREIGN KEY (Game_World_Tile_ID) REFERENCES Game_World_Tile (Game_World_Tile_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE 1 ADD CONSTRAINT FK_15 FOREIGN KEY (Game_World_ID) REFERENCES Game_World (Game_World_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Game_Tile_Image ADD CONSTRAINT FK_Game_Tile_Image3 FOREIGN KEY (Game_Tile_ID) REFERENCES Game_Tile (Game_Tile_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Player_Move ADD CONSTRAINT FK_Player_Move6 FOREIGN KEY (Player_ID) REFERENCES Player (Player_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;

