ALTER TABLE Game_World_Tile DROP CONSTRAINT FK_Game_World_Tile25;
ALTER TABLE Game_Tile DROP CONSTRAINT FK_Game_Tile23;
ALTER TABLE Game_World DROP CONSTRAINT FK_Game_World_Game_ID;
ALTER TABLE Game_Tile_Image DROP CONSTRAINT FK_Game_Tile_Image19;
ALTER TABLE Player_Move DROP CONSTRAINT FK_Player_Move22;
ALTER TABLE Player_Move DROP CONSTRAINT FK_Player_Move24;
DROP TABLE Game_World_Tile;
DROP TABLE Game_Tile;
DROP TABLE Game_World;
DROP TABLE Player;
DROP TABLE Game_Tile_Image;
DROP TABLE Player_Move;
DROP TABLE Game_room;
DROP TABLE Game;
CREATE TABLE Game_Tile (
	Name VARCHAR ( 255 ) NOT NULL,
	Game_Tile_Image VARCHAR ( 255 ) NOT NULL,
	Tile_ID INTEGER NOT NULL,
	Can_Move SMALLINT NOT NULL,
	Game_Tile_ID INTEGER NOT NULL,
	Game_World_ID INTEGER NOT NULL,
	CONSTRAINT PK_Game_Tile25 PRIMARY KEY (Game_Tile_ID)
	);
CREATE INDEX TC_Game_Tile43 ON Game_Tile (Game_World_ID );
CREATE TABLE Game (
	PK_Game_ID INTEGER NOT NULL,
	gameStar DATE NOT NULL,
	gameEnd DATE NOT NULL,
	Winner_ID INTEGER NOT NULL,
	Player1_id INTEGER NOT NULL,
	Player2_id INTEGER NOT NULL,
	World_name INTEGER NOT NULL,
	Game_ID INTEGER NOT NULL,
	CONSTRAINT TC_Game46 UNIQUE (Player2_id),
	CONSTRAINT TC_Game47 UNIQUE (World_name),
	CONSTRAINT TC_Game45 UNIQUE (Player1_id),
	CONSTRAINT PK_Game_Game_ID PRIMARY KEY (PK_Game_ID),
	CONSTRAINT TC_Game48 UNIQUE (Game_ID)
	);
CREATE TABLE Game_room (
	Game_ID INTEGER NOT NULL,
	World_name VARCHAR ( 255 ) NOT NULL,
	gameStart DATE NOT NULL,
	Player1_id INTEGER NOT NULL,
	Player2_id INTEGER NOT NULL,
	gameEnd DATE NOT NULL,
	Winner_ID INTEGER NOT NULL,
	Game_room_ID INTEGER NOT NULL,
	CONSTRAINT PK_Game_room28 PRIMARY KEY (Game_room_ID)
	);
CREATE TABLE Game_World_Tile (
	Game_World_ID INTEGER NOT NULL,
	Game_Tile_ID INTEGER NOT NULL,
	Game_World_X INTEGER NOT NULL,
	Game_World_Y INTEGER NOT NULL,
	Game_World_Tile_ID INTEGER NOT NULL,
	Game_Tile_Game_Tile_ID INTEGER NOT NULL,
	CONSTRAINT PK_Game_World_Tile26 PRIMARY KEY (Game_World_Tile_ID)
	);
CREATE INDEX TC_Game_World_Tile44 ON Game_World_Tile (Game_Tile_Game_Tile_ID );
CREATE TABLE Game_World (
	ID INTEGER NOT NULL,
	World_name INTEGER NOT NULL,
	World_size VARCHAR ( 255 ) NOT NULL,
	Game_World_ID INTEGER NOT NULL,
	PK_Game_ID INTEGER,
	CONSTRAINT PK_Game_World_ID PRIMARY KEY (Game_World_ID)
	);
CREATE INDEX idx_PK_Game_World_Game_ID ON Game_World (PK_Game_ID );
CREATE TABLE Player (
	Username VARCHAR ( 255 ) NOT NULL,
	Password VARCHAR ( 255 ) NOT NULL,
	E-mail VARCHAR ( 255 ) NOT NULL,
	Avatar VARCHAR ( 255 ) NOT NULL,
	Player_ID INTEGER NOT NULL,
	PK_Player_ID INTEGER NOT NULL,
	CONSTRAINT PK_Player19 PRIMARY KEY (PK_Player_ID)
	);
CREATE TABLE Player_Move (
	Player_ID INTEGER NOT NULL,
	Timer DATE NOT NULL,
	Game_ID INTEGER NOT NULL,
	Move_X INTEGER NOT NULL,
	Move_Y INTEGER NOT NULL,
	Player_Move_ID INTEGER NOT NULL,
	PK_Player_ID INTEGER NOT NULL,
	PK_Game_ID INTEGER NOT NULL,
	CONSTRAINT PK_Player_Move23 PRIMARY KEY (Player_Move_ID)
	);
CREATE INDEX TC_Player_Move40 ON Player_Move (PK_Player_ID );
CREATE INDEX TC_Player_Move41 ON Player_Move (PK_Game_ID );
CREATE TABLE Game_Tile_Image (
	Path VARCHAR ( 255 ) NOT NULL,
	Tile_Size VARCHAR ( 255 ) NOT NULL,
	Game_Tile_Image_ID INTEGER NOT NULL,
	Game_Tile_ID INTEGER NOT NULL,
	CONSTRAINT PK_Game_Tile_Image24 PRIMARY KEY (Game_Tile_Image_ID)
	);
CREATE INDEX TC_Game_Tile_Image42 ON Game_Tile_Image (Game_Tile_ID );
ALTER TABLE Game_World_Tile ADD CONSTRAINT FK_Game_World_Tile25 FOREIGN KEY (Game_Tile_Game_Tile_ID) REFERENCES Game_Tile (Game_Tile_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Game_Tile ADD CONSTRAINT FK_Game_Tile23 FOREIGN KEY (Game_World_ID) REFERENCES Game_World (Game_World_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Game_World ADD CONSTRAINT FK_Game_World_Game_ID FOREIGN KEY (PK_Game_ID) REFERENCES Game (PK_Game_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Game_Tile_Image ADD CONSTRAINT FK_Game_Tile_Image19 FOREIGN KEY (Game_Tile_ID) REFERENCES Game_Tile (Game_Tile_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Player_Move ADD CONSTRAINT FK_Player_Move22 FOREIGN KEY (PK_Player_ID) REFERENCES Player (PK_Player_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Player_Move ADD CONSTRAINT FK_Player_Move24 FOREIGN KEY (PK_Game_ID) REFERENCES Game (PK_Game_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;

